if(NOT "${ARCH}" STREQUAL "posix")
  if("${ARCH}" STREQUAL "arm")

    set(ZIG_TARGET arm-freestanding-eabi)
    
    if (CONFIG_CPU_CORTEX_M0)
      set(ZIG_M_CPU cortex_m0)
    elseif(CONFIG_CPU_CORTEX_M0PLUS)
      set(ZIG_M_CPU cortex_m0plus)
    elseif(CONFIG_CPU_CORTEX_M1)
      set(ZIG_M_CPU cortex_m1)
    elseif(CONFIG_CPU_CORTEX_M3)
      set(ZIG_M_CPU cortex_m3)
    elseif(CONFIG_CPU_CORTEX_M4)
      set(ZIG_M_CPU cortex_m4)
    else()
      message(FATAL_ERROR "Expected CONFIG_CPU_CORTEX_x to be defined")
    endif()
  endif()
endif()
